export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const INVALID_LOGIN = "INVALID_LOGIN";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const POPULATE_TAGS = "POPULATE_TAGS";
export const POPULATE_DISCUSSION_THREADS = "POPULATE_DISCUSSION_THREADS";
export const POPULATE_TAGS_FOR_THREAD = "POPULATE_TAGS_FOR_THREAD";